PROJECT = smtp_errand
PROJECT_DESCRIPTION = gen_errand example smtp_errand
PROJECT_VERSION = v0.0.1
DEPS = gen_errand

dep_gen_errand = git https://github.com/hnc-agency/gen_errand v0.0.1

include erlang.mk
